# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default=None, upload_to='profile_pics/')),
                ('first_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('second_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('phone', models.CharField(blank=True, default=None, max_length=48, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
