# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
