# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='session_key',
            field=models.CharField(blank=True, default=True, max_length=128, null=True),
        ),
    ]
