# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180117_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinbasket',
            options={'ordering': ('created',), 'verbose_name': 'Product in basket', 'verbose_name_plural': 'Products in basket'},
        ),
    ]
