# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171216_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
