# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180108_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operational_system',
            options={'verbose_name': 'OS', 'verbose_name_plural': 'OS'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Operational_system', verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
    ]
