# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180128_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builtinmemory',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='diagonal',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='screenresolution',
            old_name='value',
            new_name='name',
        ),
    ]
