# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180128_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='built_in_memory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='os',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_resolution',
        ),
        migrations.DeleteModel(
            name='BuiltInMemory',
        ),
        migrations.DeleteModel(
            name='Diagonal',
        ),
        migrations.DeleteModel(
            name='Operational_system',
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
        migrations.DeleteModel(
            name='Ram',
        ),
        migrations.DeleteModel(
            name='ScreenResolution',
        ),
    ]
