# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20180128_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='built_in_memory',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='diagonal',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_resolution',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
