# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20180128_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='built_in_memory',
            field=models.IntegerField(blank=True, default=None, verbose_name='Built in memory (Gb)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diagonal',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, verbose_name='Diagonal (inches)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount (percent)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_camera',
            field=models.IntegerField(blank=True, default=None, verbose_name='Main camera (Mpx)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_specifications',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.IntegerField(blank=True, default=None, verbose_name='Ram (Gb)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_resolution',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default=None, max_length=100),
        ),
    ]
